name: Enterprise CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Verify (JDBC)
    runs-on: ubuntu-latest

    # تم مسح قسم الـ services بالكامل للتخلص من فخ شبكات Docker

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # تشغيل محرك MySQL الأصلي المدمج في السيرفر وبناء الداتابيز
      - name: Start Native MySQL & Initialize Database
        run: |
          sudo systemctl start mysql.service
          mysql -u root -proot -e "
          CREATE DATABASE IF NOT EXISTS bank_system;
          USE bank_system;
          CREATE TABLE accounts (
              id VARCHAR(36) PRIMARY KEY,
              owner_name VARCHAR(100) NOT NULL,
              balance BIGINT NOT NULL,
              state VARCHAR(20) NOT NULL,
              version INT NOT NULL DEFAULT 0
          );
          CREATE TABLE transactions (
              id VARCHAR(36) PRIMARY KEY,
              type VARCHAR(20) NOT NULL,
              amount BIGINT NOT NULL,
              timestamp DATETIME NOT NULL,
              status VARCHAR(20) NOT NULL,
              rejection_reason VARCHAR(50),
              from_account_id VARCHAR(36),
              to_account_id VARCHAR(36),
              FOREIGN KEY (from_account_id) REFERENCES accounts(id),
              FOREIGN KEY (to_account_id) REFERENCES accounts(id)
          );"

      # حقن جميع المتغيرات المحتملة مباشرة في بيئة النظام
      - name: Run Integration Tests
        env:
          DB_URL: jdbc:mysql://127.0.0.1:3306/bank_system?allowPublicKeyRetrieval=true&useSSL=false
          DATABASE_URL: jdbc:mysql://127.0.0.1:3306/bank_system?allowPublicKeyRetrieval=true&useSSL=false
          DB_USER: root
          DB_USERNAME: root
          DATABASE_USER: root
          DB_PASSWORD: root
          DB_PASS: root
          DATABASE_PASSWORD: root
        run: mvn clean test